# Generated by Django 4.0.4 on 2022-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('prod_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prod_descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('prod_cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('prod_img', models.ImageField(upload_to='Productos/', verbose_name='Imagen')),
                ('prod_precio', models.IntegerField(verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['prod_id'],
            },
        ),
    ]
